_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ANCHOR_GENERATOR:
    SIZES:  [[32], [64], [128]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
  
  RPN:
    IN_FEATURES: ["p2", "p3", "p4"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 100  # Per FPN level
  # Detectron1 uses 2000 proposals per-batch,
# (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
# which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 100
INPUT:
  MIN_SIZE_TEST: 0
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
